JOTS_API_HOST="http://dev.localhost"
JOTS_API_PORT=5000
JOTS_API_KEY="zcvgxq1ixu6adznjxqn3yrlm8fxh2awb"
JOTS_API_SECRET="MrygqxFmQQtkNIQCyaSICpuBT6IAxS1tHHVAdsW2y2vsWYf2YzxhG6o6T1rHnpaw"

export JOTS_API_HOST
export JOTS_API_PORT
export JOTS_API_KEY
export JOTS_API_SECRET
